-- MySQL Script generated by MySQL Workbench
-- Wed May  4 14:11:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myDb` DEFAULT CHARACTER SET utf8 ;
USE `myDb` ;

-- -----------------------------------------------------
-- Table `myDb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myDb`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(320) NULL,
  `password` VARCHAR(200) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `uuid` VARCHAR(40) NULL,
  `activated` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDb`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myDb`.`content` (
  `contentID` VARCHAR(40) NOT NULL,
  `code` MEDIUMBLOB NULL,
  `title` VARCHAR(45) NULL,
  `description` TEXT(500) NULL,
  `date` DATE NULL,
  `tags` VARCHAR(200) NULL,
  `filename` VARCHAR(200) NULL,
  `mimetype` VARCHAR(45) NULL,
  `size` VARCHAR(8) NULL,
  `restriction` VARCHAR(10) NULL,
  `views` SMALLINT(4) NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `likes` SMALLINT(4) NULL,
  PRIMARY KEY (`contentID`),
  INDEX `fk_content_users1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_content_users1`
    FOREIGN KEY (`user_username`)
    REFERENCES `myDb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myDb`.`comment` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NULL,
  `time` DATETIME NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `content_contentID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`commentID`),
  INDEX `fk_comment_user1_idx` (`user_username` ASC) VISIBLE,
  INDEX `fk_comments_content1_idx` (`content_contentID` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `myDb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_content1`
    FOREIGN KEY (`content_contentID`)
    REFERENCES `myDb`.`content` (`contentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDb`.`deleted_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myDb`.`deleted_comment` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NULL,
  `time` DATETIME NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `content_contentID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`commentID`),
  INDEX `fk_comment_user1_idx` (`user_username` ASC) VISIBLE,
  INDEX `fk_deleted_comments_content1_idx` (`content_contentID` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user10`
    FOREIGN KEY (`user_username`)
    REFERENCES `myDb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deleted_comments_content1`
    FOREIGN KEY (`content_contentID`)
    REFERENCES `myDb`.`content` (`contentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDb`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myDb`.`asset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(10) NULL,
  `mimetype` VARCHAR(50) NULL,
  `filename` VARCHAR(50) NULL,
  `code` MEDIUMBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `myDb`;

DELIMITER $$
USE `myDb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myDb`.`comment_BEFORE_DELETE` BEFORE DELETE ON `comment` FOR EACH ROW
BEGIN
	INSERT INTO deleted_comment 
	(commentID, text, time, user_username, content_contentID)
	VALUES (old.commentID, old.text, old.time, old.user_username, old.content_contentID);
END;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
